_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    DEPTH: 18x
    FEAT_DIM: 512

DATASETS:
  NAMES: ("AIRMOT",)
  TESTS: ("AIRMOT",)

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 20
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 64

  SCHED: CosineAnnealingLR
  DELAY_EPOCHS: 10
  ETA_MIN_LR: 0.0000001

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  FREEZE_ITERS: 1000

  CHECKPOINT_PERIOD: 1

OUTPUT_DIR: logs/airmot/sbs_R18_transformer
